# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogo_prueba.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(838, 649)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        Dialog.setModal(False)
        self.historicp = QtWidgets.QPushButton(Dialog)
        self.historicp.setGeometry(QtCore.QRect(150, 400, 181, 61))
        self.historicp.setObjectName("historicp")
        self.currentpattern = QtWidgets.QPushButton(Dialog)
        self.currentpattern.setGeometry(QtCore.QRect(510, 400, 181, 61))
        self.currentpattern.setObjectName("currentpattern")
        self.quit = QtWidgets.QPushButton(Dialog)
        self.quit.setGeometry(QtCore.QRect(320, 540, 201, 41))
        self.quit.setObjectName("quit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(330, 40, 231, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(244, 120, 351, 241))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.historicp.setText(_translate("Dialog", "show historic patterns"))
        self.currentpattern.setText(_translate("Dialog", "show current patterns"))
        self.quit.setText(_translate("Dialog", "Quit"))
        self.label.setText(_translate("Dialog", "Achieve Objective Probablitiy"))
        self.label_2.setText(_translate("Dialog", "Patron pingo: 28% prob\n"
"Patrong xd: 23%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
