# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_principal_v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1194, 792)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.headshoulder = QtWidgets.QCheckBox(self.centralwidget)
        self.headshoulder.setGeometry(QtCore.QRect(150, 70, 111, 20))
        self.headshoulder.setObjectName("headshoulder")
        self.inversehs = QtWidgets.QCheckBox(self.centralwidget)
        self.inversehs.setGeometry(QtCore.QRect(290, 70, 141, 20))
        self.inversehs.setObjectName("inversehs")
        self.doubletop = QtWidgets.QCheckBox(self.centralwidget)
        self.doubletop.setGeometry(QtCore.QRect(450, 70, 121, 20))
        self.doubletop.setObjectName("doubletop")
        self.doublebottom = QtWidgets.QCheckBox(self.centralwidget)
        self.doublebottom.setGeometry(QtCore.QRect(590, 70, 111, 20))
        self.doublebottom.setObjectName("doublebottom")
        self.ascendingtriangle = QtWidgets.QCheckBox(self.centralwidget)
        self.ascendingtriangle.setGeometry(QtCore.QRect(740, 70, 141, 20))
        self.ascendingtriangle.setObjectName("ascendingtriangle")
        self.descendingtriangle = QtWidgets.QCheckBox(self.centralwidget)
        self.descendingtriangle.setGeometry(QtCore.QRect(910, 70, 141, 20))
        self.descendingtriangle.setObjectName("descendingtriangle")
        self.windowsize = QtWidgets.QLineEdit(self.centralwidget)
        self.windowsize.setGeometry(QtCore.QRect(220, 210, 113, 22))
        self.windowsize.setText("")
        self.windowsize.setObjectName("windowsize")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 165, 131, 31))
        self.label.setObjectName("label")
        self.initialdate = QtWidgets.QDateEdit(self.centralwidget)
        self.initialdate.setGeometry(QtCore.QRect(520, 200, 110, 22))
        self.initialdate.setObjectName("initialdate")
        self.enddate = QtWidgets.QDateEdit(self.centralwidget)
        self.enddate.setGeometry(QtCore.QRect(710, 200, 110, 22))
        self.enddate.setObjectName("enddate")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 160, 101, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(710, 160, 111, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(500, 290, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(480, 350, 251, 61))
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 460, 221, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(600, 460, 181, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1194, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.headshoulder.setText(_translate("MainWindow", "Head shoulder"))
        self.inversehs.setText(_translate("MainWindow", "inverse h&s"))
        self.doubletop.setText(_translate("MainWindow", "double top"))
        self.doublebottom.setText(_translate("MainWindow", "double bottom"))
        self.ascendingtriangle.setText(_translate("MainWindow", "ascending triangle"))
        self.descendingtriangle.setText(_translate("MainWindow", "descending triangle"))
        self.label.setText(_translate("MainWindow", "Tamaño de ventana"))
        self.label_2.setText(_translate("MainWindow", "Fecha inicial"))
        self.label_3.setText(_translate("MainWindow", "Fecha final"))
        self.pushButton.setText(_translate("MainWindow", "Open File"))
        self.label_4.setText(_translate("MainWindow", "Selected file: Ninguno"))
        self.pushButton_2.setText(_translate("MainWindow", "Mostrar Patrones Historicos"))
        self.pushButton_3.setText(_translate("MainWindow", "Mostrar Patrones actuales"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
