# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui_files/ventana_principal_v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1194, 792)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.head_and_shoulders = QtWidgets.QCheckBox(self.centralwidget)
        self.head_and_shoulders.setGeometry(QtCore.QRect(150, 70, 111, 20))
        self.head_and_shoulders.setObjectName("head_and_shoulders")
        self.inv_head_and_shoulders = QtWidgets.QCheckBox(self.centralwidget)
        self.inv_head_and_shoulders.setGeometry(QtCore.QRect(290, 70, 141, 20))
        self.inv_head_and_shoulders.setObjectName("inv_head_and_shoulders")
        self.double_top = QtWidgets.QCheckBox(self.centralwidget)
        self.double_top.setGeometry(QtCore.QRect(450, 70, 121, 20))
        self.double_top.setObjectName("double_top")
        self.double_bottom = QtWidgets.QCheckBox(self.centralwidget)
        self.double_bottom.setGeometry(QtCore.QRect(590, 70, 111, 20))
        self.double_bottom.setObjectName("double_bottom")
        self.ascending_triangle = QtWidgets.QCheckBox(self.centralwidget)
        self.ascending_triangle.setGeometry(QtCore.QRect(740, 70, 141, 20))
        self.ascending_triangle.setObjectName("ascending_triangle")
        self.descending_triangle = QtWidgets.QCheckBox(self.centralwidget)
        self.descending_triangle.setGeometry(QtCore.QRect(910, 70, 141, 20))
        self.descending_triangle.setObjectName("descending_triangle")
        self.windowsize = QtWidgets.QLineEdit(self.centralwidget)
        self.windowsize.setGeometry(QtCore.QRect(220, 210, 113, 22))
        self.windowsize.setText("")
        self.windowsize.setObjectName("windowsize")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 165, 131, 31))
        self.label.setObjectName("label")
        self.initialdate = QtWidgets.QDateEdit(self.centralwidget)
        self.initialdate.setGeometry(QtCore.QRect(520, 200, 110, 22))
        self.initialdate.setObjectName("initialdate")
        self.enddate = QtWidgets.QDateEdit(self.centralwidget)
        self.enddate.setGeometry(QtCore.QRect(710, 200, 110, 22))
        self.enddate.setObjectName("enddate")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 160, 101, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(710, 160, 111, 31))
        self.label_3.setObjectName("label_3")
        self.openfilebtn = QtWidgets.QPushButton(self.centralwidget)
        self.openfilebtn.setGeometry(QtCore.QRect(500, 290, 93, 28))
        self.openfilebtn.setObjectName("openfilebtn")
        self.selectedfile = QtWidgets.QLabel(self.centralwidget)
        self.selectedfile.setGeometry(QtCore.QRect(400, 350, 481, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.selectedfile.setFont(font)
        self.selectedfile.setObjectName("selectedfile")
        self.historicpatternsbtn = QtWidgets.QPushButton(self.centralwidget)
        self.historicpatternsbtn.setGeometry(QtCore.QRect(310, 460, 221, 51))
        self.historicpatternsbtn.setObjectName("historicpatternsbtn")
        self.currentpatternsbtn = QtWidgets.QPushButton(self.centralwidget)
        self.currentpatternsbtn.setGeometry(QtCore.QRect(600, 460, 181, 51))
        self.currentpatternsbtn.setObjectName("currentpatternsbtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1194, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.head_and_shoulders.setText(_translate("MainWindow", "Head shoulder"))
        self.inv_head_and_shoulders.setText(_translate("MainWindow", "inverse h&s"))
        self.double_top.setText(_translate("MainWindow", "double top"))
        self.double_bottom.setText(_translate("MainWindow", "double bottom"))
        self.ascending_triangle.setText(_translate("MainWindow", "ascending triangle"))
        self.descending_triangle.setText(_translate("MainWindow", "descending triangle"))
        self.label.setText(_translate("MainWindow", "Tamaño de ventana"))
        self.label_2.setText(_translate("MainWindow", "Fecha inicial"))
        self.label_3.setText(_translate("MainWindow", "Fecha final"))
        self.openfilebtn.setText(_translate("MainWindow", "Open File"))
        self.selectedfile.setText(_translate("MainWindow", "Selected file: Ninguno"))
        self.historicpatternsbtn.setText(_translate("MainWindow", "Mostrar Patrones Historicos"))
        self.currentpatternsbtn.setText(_translate("MainWindow", "Mostrar Patrones actuales"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
